version: "3.9"
services:
  db:
    container_name: db
    build: ./mysql
    restart: always
    ports:
      - 3306:3306
    networks:
      - app_network
  
  dbms:
    container_name: dbms
    image: phpmyadmin:5.2.1
    restart: always
    environment:
      PMA_HOST: db
    ports:
      - 8080:80
    networks:
      - app_network

  server:
    container_name: server
    build: ./server
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
    depends_on:
      - db
  
  inferapi:
    container_name: inferapi
    build: ./inferapi
    restart: always
    ports: 
      - 8000:8000
    networks:
      - app_network
    depends_on:
      - server
    
networks:
  app_network:
    driver: bridge
    